nelmio_cors:
  defaults:
    allow_origin: ['*']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    max_age: 3600
  paths:
    '^/userCreate': 
      allow_origin: ['*']
      allow_headers: ['Content-Type']
      allow_methods: ['GET', 'POST', 'OPTIONS']
      max_age: 3600
