controllers:
    resource: ../src/Controller/
    type: attribute

api_login_check:
    path: /api/login_check

react_frontend:
    path: /{reactRouting}
    controller: App\Controller\DefaultController::index
    requirements:
        reactRouting: "^(?!api/).*"
